name: Update Rules
on:
  schedule:
    - cron: '0 20,8 * * *'
  push:
  workflow_dispatch:


jobs:
  Pushed:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: actions/checkout@main           
      - name: Update Rules
        run: |
          bash ./script/mian.sh
